## Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
sent = [' the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good'
        ]

In [ ]:
sent

[' the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
### Vocablary Size
voc_size=10000

In [ ]:
one_hot_repr = [one_hot(words,voc_size) for words in sent]

In [ ]:
print(one_hot_repr)

[[7877, 4449, 1046, 9630], [7877, 4449, 1046, 9714], [7877, 1876, 1046, 2196], [3590, 6731, 7791, 6618, 3069], [3590, 6731, 7791, 6618, 7491], [6135, 7877, 6370, 1046, 9957], [7315, 2197, 670, 6618]]


## Word Embedding representation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7877 4449 1046 9630]
 [   0    0    0    0 7877 4449 1046 9714]
 [   0    0    0    0 7877 1876 1046 2196]
 [   0    0    0 3590 6731 7791 6618 3069]
 [   0    0    0 3590 6731 7791 6618 7491]
 [   0    0    0 6135 7877 6370 1046 9957]
 [   0    0    0    0 7315 2197  670 6618]]


In [ ]:
# Dim
dim = 10

In [ ]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 7877, 4449, 1046, 9630], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 16ms/step


array([[-0.03552632,  0.00440619,  0.02180452, -0.04938716,  0.00628368,
         0.03577663, -0.01314538, -0.01036487, -0.01983113,  0.04604248],
       [-0.03552632,  0.00440619,  0.02180452, -0.04938716,  0.00628368,
         0.03577663, -0.01314538, -0.01036487, -0.01983113,  0.04604248],
       [-0.03552632,  0.00440619,  0.02180452, -0.04938716,  0.00628368,
         0.03577663, -0.01314538, -0.01036487, -0.01983113,  0.04604248],
       [-0.03552632,  0.00440619,  0.02180452, -0.04938716,  0.00628368,
         0.03577663, -0.01314538, -0.01036487, -0.01983113,  0.04604248],
       [ 0.03716815,  0.0228782 , -0.02787025,  0.03055601,  0.0352588 ,
        -0.02435155, -0.03666053,  0.00079419, -0.03713768, -0.03996487],
       [ 0.03999765,  0.02610291, -0.04588012,  0.01136695,  0.00981395,
        -0.01458291,  0.01568513, -0.04271355,  0.04132248,  0.03840644],
       [ 0.01248282, -0.04145478, -0.03739711, -0.01478202, -0.00053271,
        -0.02592677, -0.00044391,  0.02359496

In [ ]:
### Assignment
sent = [
    "The world is a better place",
    "Marvel series in my favourite movies",
    "I like DC movies",
    "the cat is eating the food",
    "Tom and jerry is my favourite movie",
    "Python is my favourite programming language"
]

In [ ]:

voc_size=10000
one_hot_repr = [one_hot(words,voc_size) for words in sent]

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [ ]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')
model.summary()

[[   0    0 7877 3782   31 7791 4023 8415]
 [   0    0 3489 2698 5865 8561  692 6427]
 [   0    0    0    0 3590 1137 9437 6427]
 [   0    0 7877 3709   31 4871 7877 7382]
 [   0 4040 7294 3798   31 8561  692  552]
 [   0    0 9462   31 8561  692 7435 4763]]
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 47ms/step


array([[-0.03266869, -0.01553877,  0.02566418,  0.02525205,  0.00069519,
        -0.02832857, -0.03889417,  0.01518636, -0.03738189,  0.03274937],
       [-0.03266869, -0.01553877,  0.02566418,  0.02525205,  0.00069519,
        -0.02832857, -0.03889417,  0.01518636, -0.03738189,  0.03274937],
       [ 0.03001856, -0.04808968,  0.02041713, -0.04091223, -0.00672978,
        -0.0129264 , -0.02257233, -0.03412315, -0.04444612, -0.01899313],
       [ 0.01186746,  0.04752572,  0.01285296, -0.01138346, -0.00370228,
        -0.01773094, -0.04669612, -0.02239048, -0.0491321 , -0.04589176],
       [-0.03404491, -0.0164592 ,  0.01097203, -0.03730882,  0.01630635,
        -0.00994907, -0.04969192,  0.04344568,  0.03170556, -0.04646111],
       [ 0.03780681,  0.04417542, -0.01377577, -0.01974171,  0.01627826,
        -0.03869721, -0.02275071, -0.03792029, -0.04690573, -0.04060451],
       [-0.01736184,  0.01594647, -0.0080318 , -0.01645646,  0.04669813,
         0.00402231,  0.04823854, -0.00578035

In [ ]:
embedded_docs[0]

array([   0,    0, 7877, 3782,   31, 7791, 4023, 8415], dtype=int32)